### ISSUE TITLE
Modprobe: command not found

### ISSUE THREAD

**Issue by Psuedoo** [hocus-dev/hocus#121]
## 🐛 Bug description

Ran the suggested startup command,
```bash
git clone https://github.com/hocus-dev/hocus.git
cd hocus
# HOCUS_HOSTNAME is the hostname of the machine where you are deploying Hocus
# If you are running Hocus locally, set it to "localhost"
# If you are running Hocus on a remote server, set it to the hostname of the server
HOCUS_HOSTNAME="localhost" ops/bin/local-up.sh
```

and got:

```bash
hocus-local-hocus-ui-1  | Using 'form_post' for response_mode may cause issues for you logging in over http, see https://github.com/auth0/express-openid-connect/blob/master/FAQ.md
hocus-local-hocus-ui-1  | Express server listening on port 3000
hocus-local-hocus-agent-1  | Trying to load target_core_user
hocus-local-hocus-agent-1  | ./setup-tcmu.sh: line 17: modprobe: command not found
```

Also, I might add that `modprobe` is a command on the system when running it manually.

## Environment

- Hocus version (commit hash)
- 5c0aa0375d19ce3d294287b7a645362a5579d655

- OS and its version
- Ubuntu Server  22.04.2 LTS x86_64

- Any other environment information that may help
- Running in a vm in proxmox but using host cpu for kvm acceleration

**Comment by gorbak25** [comment]
@Psuedoo Thank you for reporting this issue. Please feel free to check out the master branch and report if it fixes your issue.
