### ISSUE TITLE
unknown flag error

### ISSUE THREAD

**Issue by AugustasV** [hocus-dev/hocus#135]
## 🐛 Bug description

Followed hocus quick start guide, but got that error than trying to run on my linux machine
```
namai@parrot ~/hocus (main)
$ HOCUS_HOSTNAME="localhost" ops/bin/local-up.sh
Pulling docker images 📥 - ❌ in 1.23
unknown flag: --ignore-buildable

Above you will find the logs
Please report this problem here
🙏🙏🙏  https://github.com/hocus-dev/hocus/issues/new/choose  🙏🙏🙏

```
## Environment

- Hocus version (commit hash) latest ca0133326b445c1143ab622a46da451c4503737e
- Parrot OS 5.3 (Electro Ara) Kernel 6.1.0-1parrot1-amd64
- Any other environment information that may help

**Comment by regner** [comment]
See this issue: https://github.com/hocus-dev/hocus/issues/11

Running `sudo apt install --only-upgrade docker-compose-plugin` may fix your issue.

**Comment by regner** [comment]
It might be a good idea for the `ops/bin/local-up.sh` script to check the version of Docker compose, rather than just if it is installed.

https://github.com/hocus-dev/hocus/blob/main/ops/bin/local-up.sh#L76

**Comment by regner** [comment]
It appears that `--ignore-buildable` was added with v2.15.0, released Jan. 5th: https://github.com/docker/compose/releases/tag/v2.15.0

**Comment by regner** [comment]
A possible solution:

```bash
# Check minimum version of docker compose
# We require docker compose of at least version 2.15.0 which introduced --ignore-buildable
COMPOSE_VERSION="$(docker compose version | grep -o -E '[0-9]+(\.[0-9]+){2}$')"
COMPOSE_REQUIRED_VERSION="2.15.0"
if ! [ "$(printf '%s\n' "$COMPOSE_REQUIRED_VERSION" "$COMPOSE_VERSION" | sort -V | head -n1)" = "$COMPOSE_REQUIRED_VERSION" ]; then 
  echo "Less than ${COMPOSE_REQUIRED_VERSION}"
fi
```

**Comment by gorbak25** [comment]
@regner Thank you for suggesting a fix! --ignore-buildable  is only needed when building the containers locally. After #120 got  merged that flag is not needed when pulling the agent/ui/setup images from quay. Will make a PR today which will remove the flag when using prebuild images, otherwise it will do a docker-compose version check.
